services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JPMSchuler\ShowPageEditors\:
    resource: '../Classes/*'

  JPMSchuler\ShowPageEditors\Command\ShowBackendVisibilityOfPage:
    tags:
      - name: 'console.command'
        command: 'page:showVisibilityFor'
        schedulable: false
